### ISSUE TITLE
Application Not Found even when symlink exists

### ISSUE THREAD

**Issue by Arcath** [basecamp/pow#145]
I have a app a www.spaics and api.spacis, neither of them are working whilst my other symlinks are.

I've updated my pow install to the latest version (0.3.1)but still I just get an error when I go to www.spacis.dev in safari, these symlinks have worked in that past and I'm not sure why they would just stop working.

The symlinks still work and if i `cd ~/.pow/www.spacis` I get the code for my app.

**Comment by sidhene** [comment]
None of these worked for me.

**Comment by anthonyto** [comment]
For anyone still having trouble: This was indirectly mentioned above, but make sure that you did NOT manually create the `.pow` folder. Doing something like `mkdir .pow` will not work. The `.pow` folder must be symlinked to `/Users/<user>/Library/Application Support/Pow/Hosts`, so either let pow create the `.pow` folder on its own during installation, or manually symlink the `.pow` folder accordingly.
