### ISSUE TITLE
rake db:drop pgsql "database in use"

### ISSUE THREAD

**Issue by JeanMertz** [basecamp/pow#212]
Not sure if this is related to the `pow`, `powder` or `pg` gem, but whenever I want a 100% clean slate on my development app I usually do:

```
rake db:drop:all
rake db:create
rake RAILS_ENV=test db:create
rake db:migrate
rake RAILS_ENV=test db:migrate
```

However, when using `postgresql` with `pow` and managing pow through the `powder` command-line tool, I get the error `database in use` when I try to drop the database.

This happens even if I do any combination of `powder down`, `powder restart` or `powder remove`. The only solution I've found is to go into the os x activity window and close the `pow` session. Even though the session is automatically restarted (and shows up again in the list) I can still drop the database after this action.

Can this somehow be fixed to make it easier to drop a database in use by `pow`?

**Comment by falconed** [comment]
Thanks for the solutions!  I packed this up in a gem called pgreset, including support for older versions of postgresql, at https://rubygems.org/gems/pgreset.  Source is available at https://github.com/falconed/pgreset.

**Comment by manuelmeurer** [comment]
Nice, I updated my blog post to mention this gem!
