### ISSUE TITLE
Stopping pow from working on .dev

### ISSUE THREAD

**Issue by jackfranklin** [basecamp/pow#272]
Hey,

So I have MAMP set up on my Macbook and have a tonne of virtual hosts set up for all my development sites. These all end in *.dev, which has prevented me installing Pow before as I figuredI would have issues.

I then discovered the `POW_DOMAINS` option which I have set to:

```
export POW_DOMAINS=rails
```

And going to `myapp.rails` works fine, and going to `myapp.dev` does not, it 404s (which is what I want).

However, if I go to the URL of one of my VHosts, eg `myphpapp.dev`, I get the "Pow is Installed" page. More interestingly, the settings on that page even tell me to go to `.rails`:

```
$ cd ~/.pow
$ ln -s /path/to/myapp
$ open http://myapp.rails/
```

Are the instructions given on that page.

So the question is, it is possible to get Pow to completely ignore *.dev domains, as I seem to be nearly but not quite there right now?

Thanks,

Jack.

**Comment by hew** [comment]
The docs should be updated to reflect the above. I just wasted some time trying to change the domain away from `.dev`, only to find that it's seemingly impossible by following the instructions on the website.
