### ISSUE TITLE
Bundler::GemNotFound: Could not find multi_json-1.0.4 in any of the sources

### ISSUE THREAD

**Issue by alanhogan** [basecamp/pow#278]
In one of my Rails apps, I’m getting:

> ### Error starting application
> 
> Your Rack app raised an exception when Pow tried to run it.
> 
> ```
>    Bundler::GemNotFound: Could not find multi_json-1.0.4 in any of the sources
>    ~/.rvm/gems/ruby-1.9.3-p125/gems/bundler-1.1.3/lib/bundler/spec_set.rb:90:in `block in materialize'
>    [...]
> ```
### Interesting / Details / Tried:
- This happens in one (big, complex) rails app, and not in another one.
- This one has an `.rvmrc` file and the other app does not.
- I have no problems running the app outside of `pow` with `rackup -p 3000` (or just `bundle exec rails s`).
- I am using Pow + Apache.
- I am using the latest `bundler` and `rvm`.

**Comment by knagode** [comment]
rvm env . -- --env > .powenv

Returns 'Unrecognized command line argument(s): '. --env' ( see: 'rvm usage' )'. Any other idea?
