### ISSUE TITLE
Pow ignoring rbenv gemset, causing Bundler::GemNotFound errors

### ISSUE THREAD

**Issue by cobyism** [basecamp/pow#284]
Firstly, I know there's already some similar issues raised about these kinds of errors, however the discussions I've found have all been somewhat RVM-centric, but I'm using rbenv instead and so very few of the suggestions in those issues apply to my situation. Here's what I'm seeing...

When I use `rails s` to serve an app, rails respects rbenv's version and gemset and serves up the app without complaint:

``` sh
$ cd ~/.pow/myapp
$ bundle install
...
Your bundle is complete! [...]
$ rails s
=> Booting WEBrick
=> Rails 3.1.2 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
```

But when I browse to `http://myapp.dev/` I get the following error:

```
Error starting application
Your Rack app raised an exception when Pow tried to run it.

---
Bundler::GemNotFound: Could not find multi_json-1.1.0 in any of the sources
/Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/spec_set.rb:90:in `materialize'
/Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/spec_set.rb:83:in `map!'
/Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/spec_set.rb:83:in `materialize'
/Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/definition.rb:127:in `specs'
/Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/definition.rb:172:in `specs_for'
...
```

I receive this error regardless of what ruby version/gemset I specify using rbenv. I've tried setting the local ruby version to each of the versions listed below (and running `bundle install` afterwards each time) but to no avail:

``` sh
$ rbenv versions
  1.8.7-p352
  1.9.2-p290
* 1.9.3-p0 (set by /Users/coby/.pow/myapp/.rbenv-version)
  ree-1.8.7-2011.03
```

I've even tried doing `rbenv local system` (and `bundle install`) but it still doesn't seem to find the gems—so I have no idea where Pow is looking!

Environment wise:
- I'm on OSX 10.7.3
- using Zsh
- have rbenv version 0.3.0 with the ruby versions listed above all installed via ruby-build.

Any suggestions for how I can resolve this?

**Comment by nathanhamilton** [comment]
I had this same issue today and I finally deleted my `~/.ruby-version` which was created several days ago. Evidently everything was fine with my rbenv and pow, however pow was serving up `~/.ruby-version` file set to ruby 2.2.0 which caused bundler to look in `~/.rbenv/versions/2.2.0/lib/ruby/gems`  instead of `~/.rbenv/versions/2.2.3/lib/ruby/gems` for gem loading. Ruby 2.2.3 is what I have set rbenv to locally. Deleting the `~/.ruby-version` file fixed the issue.
