### ISSUE TITLE
Capture and display stdout/stderr when a process fails to boot

### ISSUE THREAD

**Issue by mguterl** [basecamp/pow#30]
Browser output:

/Users/michaelguterl/code/rm/board raised an exception during boot.
Error: unknown process error
Error: unknown process error
    at Process.<anonymous> (/Users/michaelguterl/Library/Application Support/Pow/Versions/0.2.2/node_modules/nack/lib/process.js:115:39)
    at Socket.<anonymous> (/Users/michaelguterl/Library/Application Support/Pow/Versions/0.2.2/node_modules/nack/lib/process.js:3:63)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:672:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

Log output:

[Fri, 08 Apr 2011 00:18:24 GMT] DEBUG nack worker 505 spawned
[Fri, 08 Apr 2011 00:18:38 GMT] DEBUG nack worker exited
[Fri, 08 Apr 2011 00:18:51 GMT] DEBUG nack worker 625 spawned
[Fri, 08 Apr 2011 00:19:04 GMT] DEBUG nack worker exited

Any ideas?

**Comment by trevorturk** [comment]
Future Googlers, I ran into this problem and left some notes over here, too: https://github.com/rails/rails/issues/18660#issuecomment-95593625

In my case, the problem was that the symlink to my Rails app had the incorrect capitalization, (`~/sites/example` instead of `~/Sites/example`) but it was difficult to track down, and I was only able to see the underlying problem by wrapping `initialize!` in `config/environment.rb` in a rescue block like so:

```ruby
# Initialize the rails application
begin
  Example::Application.initialize!
rescue Exception => e
  raise e.inspect
end
```

**Comment by pietervisser** [comment]
We had the same problem, and solved it by changing the capitalization in the symlink:

Our app is located at `~/Dev/Apps/example`
The symlink was also pointing at `~/Dev/Apps/example`, but this raised the 'unknown process error'.

As @trevorturk suggested, we wrapped the initialize! in a rescue block. After some debugging, we found that rails tried to auto load files from `~/Dev/apps/example` (notice the `apps` vs `Apps`).

After symlinking to `~/Dev/apps/example` everything worked fine, but this behavior is very strange as the real name of the directory is `Apps`, not `apps`. To prevent more issues in the future we renamed the Apps directory to apps.

**Comment by trevorturk** [comment]
@pietervisser the trick is to make sure your pow symlink and directory name match exactly. I'm glad my notes helped someone! :grin:

**Comment by pietervisser** [comment]
@trevorturk as I tried to explain, in our case that did not work. We explicitly needed to use a *different* symlink as opposed to the directory name. Though, your rescue block did help us out!

**This did not work**
Real directory: `~/Dev/Apps/example`
Symlink: `~/Dev/Apps/example`

**This does work**
Real directory: `~/Dev/Apps/example`
Symlink: `~/Dev/apps/example`

**Comment by trevorturk** [comment]
Weird! Anyway, glad you sorted it out!

**Comment by techsethi** [comment]
I was getting this error because of syntax error in config/routes.rb

but POW didn't show the exact cause.

Doing rails s , showed the error & I fixed it.

**Comment by colinweight** [comment]
If it helps anyone, I had this error after I'd copied a dev db in Postgres and had a typo in the database name.

**Comment by NielsKSchjoedt** [comment]
Check if your DB is running. Im my case postgresql wasn't started
