### ISSUE TITLE
Gem::LoadError: You have already activated json 1.8.0, but your Gemfile requires json 1.7.7. Using bundle exec may solve this.

### ISSUE THREAD

**Issue by darthdeus** [basecamp/pow#378]
This is somewhat similar to #374, but I haven't changed anything about BUNDLE_GEMFILE.

The troubleshooting page says to include this in the `config.ru`, but it doesn't seem to do anything for me

``` ruby
require 'rubygems'
require 'bundler'
Bundler.setup
```

**Comment by limin13215** [comment]
# This is what I did to resolve this problem:
> $ gem list json

json (2.1.0 , 1.8.6,  1.8.1)
> $ gem uninstall json -v2.1.0

Successfully uninstalled json-2.1.0

**Comment by nathantech2005** [comment]
I can't uninstall the newer json gem because it's marked as the default gem.

**Comment by blckjack** [comment]
came up with solution to downgrade ruby itself, where json bundled to version I need.
Ruby 2.3.0-2.3.4 -> json 1.8.3(as default)
