### ISSUE TITLE
Pow will need a new TLD soon

### ISSUE THREAD

**Issue by indirect** [basecamp/pow#386]
Turns out that .dev is going to become a legit TLD sometime in the next year: https://www.gandi.net/domain/gtld/dev/news

It's already not safe to use .local because of Bonjour, so... now what?

**Comment by l15n** [comment]
Looks like `.dev` is now on the IANA's root zone database as of Jan 7, 2015

https://www.iana.org/domains/root/db

Trying to install gems with pow setup leads to errors like

```
$ gem install bundler -v 1.7.13
??ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Operation timed out - connect(2) (https://your-dns-needs-immediate-attention.dev/quick/Marshal.4.8/bundler-1.7.13.gemspec.rz)
```

**Comment by guidobouman** [comment]
@sstephenson @sj26 ?

**Comment by sandstrom** [comment]
ping @sstephenson @sj26 What do you think of a blanket switch to `.pow` as a quick fix (essentially a search/replace of the string).

**Comment by khoan** [comment]
```
$ dig issue.dev A +short
127.0.53.53
$ dig issue.dev TXT +short
"Your DNS configuration needs immediate attention see https://icann.org/namecollision"
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109
```

**Comment by jeremy** [comment]
Switched from `.dev` to `.test` #547
