### ISSUE TITLE
json gem loads before config.ru, causes bundler error

### ISSUE THREAD

**Issue by julian7** [basecamp/pow#416]
I have a ruby environment with json-1.7.7, but my app's Gemfile requires json-1.8.1. I use `bundle install --path ...`, which puts gems to a separate folder, and those gems are not available outside of the bundled environment.

This results the following error:

**Gem::LoadError: You have already activated json 1.7.7, but your Gemfile requires json 1.8.1. Using bundle exec may solve this.**

After a careful look at the booting process I figured out nack_worker does require json before it loads config.ru.

`gem install json -v 1.8.1` made it work, but it doesn't seem like a reliable solution to me.

**Comment by techsethi** [comment]
I had multiple json version installed. 

`gem list json`

showed 2 versions

removed the un-nesseccary verion

`gem uninstall json -v 1.8.1 `

and it worked fine.
