### ISSUE TITLE
.powenv or Rack middleware for arbitrary headers

### ISSUE THREAD

**Issue by jxpx777** [basecamp/pow#426]
It would be great if Pow supported some mechanism for apps to add headers to requests. .powenv or Rack middleware seem to be the best way to do this so that the headers can be specified at the application level. My main motivation for this is to allow setting the Access-Control-Allow-Origin header for CORS support in my dev environment, loading content from one app in another.

**Comment by walter** [comment]
@jeremy unless I'm mistaken rack-cors won't work for static files under public with pow. Am I missing something?

**Comment by walter** [comment]
To clarify, what I mean is that when pow encounters a static file, even for a rack application like Rails, it just serves the file without engaging the rack app at all.

In other words rack-ocrs is only a partial solution as it only handles requests that go through the rack app. If pow encounters a static file rack-cors isn't involved.

At least that is my reading of https://github.com/basecamp/pow/blob/278593fe21f70eb8d5b39419404c81db1d232660/src/http_server.coffee#L148-L161.

Happy to be corrected if I've misinterpreted the code.

**Comment by chrismetcalf** [comment]
:+1: here. I'm encountering the same problem as @walter

**Comment by jeremy** [comment]
+1. Would do a PR to allow disabling static file service entirely so you can implement way you like within the app itself. Doing per-site static file service customization within Pow probably won't fly.

**Comment by temirov** [comment]
+1
