### ISSUE TITLE
Yosemite Support

### ISSUE THREAD

**Issue by mhodgson** [basecamp/pow#452]
Unfortunately, Yosemite breaks pow because ipfw has been completely removed from the OS. I was able to get pow working again using PF, which is the new recommended way to do port forwarding in OS X. Here's what I did to get it working:

First, add an anchor file to contain the pow port forwarding rule. Place the following code in /etc/pf.anchors/com.pow:

```
rdr pass on lo0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 20559

```

NOTE: The trailing line break is required. Otherwise pf will say you have a syntax error.

Next, add two lines to /etc/pf.conf to load your new rule. It is important where these lines go. Add this line right after `rdr-anchor "com.apple/*"`:

```
rdr-anchor "pow"
```

Add this line directly after `load anchor "com.apple" from "/etc/pf.anchors/com.apple"`:

```
load anchor "pow" from "/etc/pf.anchors/com.pow"

```

Again, make sure to maintain the final line break.

Next, reload the rules into pf by running `sudo pfctl -f /etc/pf.conf`

Finally, enable pf by running `sudo pfctl -e`

Interested to hear how other people fare with this. I would provide a pull request but I'm not familiar with the internals of pow or the way this should be implemented.

**Comment by zirni** [comment]
@allolex solutions worked for me.
But needed to restart my dns resolver as suggested on pow's troubleshooting site
https://github.com/basecamp/pow/wiki/Troubleshooting

```
$ scutil --dns
$ sudo touch /etc/resolver/dev # did the trick
```

**Comment by sescotti** [comment]
If this solution is preventing Tomcat to start, com.pow file should look like this:

rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 80 -> 127.0.0.1 port 8080
rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 443 -> 127.0.0.1 port 8443
rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 8080 -> 127.0.0.1 port 8080
rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 8443 -> 127.0.0.1 port 8443

**Comment by superfighter** [comment]
thanks @mhodgson

**Comment by manuchap** [comment]
http://alpha.logdown.com/posts/218221-fix-the-pow-cant-start-in-osx-yosemite-1010

**Comment by onedanshow** [comment]
@allolex Thanks for posting your solution! I was doing the same thing

**Comment by brewster1134** [comment]
so should this work out of the box now with 0.3.0?  i have tried several of these solutions manually, but to no avail.

**Comment by koenpunt** [comment]
Why would you still be using 0.3.0? 0.5.0 is the latest version of Pow.

But, if 0.3.0 uses the same port, which I guess it does, then the PF rule should work just fine.

What's your OS version?

**Comment by brewster1134** [comment]
sorry that was a typo... i am on 0.5.0. OSX 10.10.4

**Comment by aguynamedben** [comment]
FWIW @zirni's DNS reset solution worked for me. I'm not sure why this happens.

    $ scutil --dns
    $ sudo touch /etc/resolver/dev # did the trick

One other thing to look out for... I my zsh/bash config [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) periodically self-checks for updates when a new shell is started. If if finds new updates, it goes into a "Do you want to upgrade? Y/n" prompt

If I restart pow during a time when zsh decides it needs to update itself, pow hangs. I have to `ps aux | grep pow`, `kill <pid>`, etc. Then open a new tab in iTerm, agree to the updates, then start pow again. It looks like pow runs within your shell, so if anything is keeping your shell from starting and handing pow control, that could be causing silent/failed/hanged starts.

**Comment by brewster1134** [comment]
DNS reset did not work for me. also played around with oh-my-zsh update issues... still `ERR_CONNECTION_REFUSED`

**Comment by nodesocket** [comment]
Tested in El Capitan and seems to work. Here is a little copy and paste guide which should work:

````shell
sudo tee /etc/pf.anchors/com.pow > /dev/null <<'EOF'
rdr pass on lo0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8888
rdr pass on lo0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 4444

EOF
````

Then:

````shell
sudo tee /etc/pf.conf > /dev/null <<'EOF'
#
# com.apple anchor point
#
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
rdr-anchor "pow"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "pow" from "/etc/pf.anchors/com.pow"

EOF
````

Finally:

````shell
sudo pfctl -f /etc/pf.conf
sudo pfctl -e
````

**Comment by koenpunt** [comment]
@nodesocket The default setup should work fine on El Capitan. Also, you refer to non-standard ports in your "copy and paste guide".

**Comment by krishnarohitreddy** [comment]
thank you this worked for me :-)

**Comment by Wissam-Halimi** [comment]
this is super! easiest copy paste I've ever done! Thanks!!!

**Comment by davidhq** [comment]
Thank you so much...

**Comment by YiHuaTian** [comment]
ykhddeiMac:etc ykhd$ sudo pfctl -f /etc/pf.conf
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
ykhddeiMac:etc ykhd$ sudo pfctl -e
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled

**Comment by YiHuaTian** [comment]
#
# com.apple anchor point
#
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
rdr-anchor "pow"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "pow" from "/etc/pf.anchors/com.pow"

**Comment by YiHuaTian** [comment]
rdr pass on lo0 inet proto tcp from any to any port 10080 -> 192.168.99.100 port 10080

**Comment by YiHuaTian** [comment]
ykhddeiMac:etc ykhd$ sudo pfctl -f /etc/pf.conf
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
ykhddeiMac:etc ykhd$ sudo pfctl -e
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled

this is why？ OSX 10.11.3

**Comment by YiHuaTian** [comment]
@koenpunt

**Comment by YiHuaTian** [comment]
#
# com.apple anchor point
#
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
rdr-anchor "pow"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "pow" from "/etc/pf.anchors/com.pow"

**Comment by YiHuaTian** [comment]
scrub-anchor "com.apple/*"
nat-anchor "com.apple/*"
rdr-anchor "com.apple/*"
rdr-anchor "pow"
dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "pow" from "/etc/pf.anchors/com.pow"

**Comment by koenpunt** [comment]
You shouldnt mess with `/etc/pf.conf` IMHO

**Comment by YiHuaTian** [comment]
@koenpunt What do you mean?

**Comment by YiHuaTian** [comment]
add two lines to /etc/pf.conf to load your new rule ，you said

**Comment by YiHuaTian** [comment]
@mhodgson 

rdr pass on lo0 inet proto tcp from any to any port 10080 -> 192.168.99.100 port 10080

scrub-anchor "com.apple/"
nat-anchor "com.apple/"
rdr-anchor "com.apple/"
rdr-anchor "pow"
dummynet-anchor "com.apple/"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"
load anchor "pow" from "/etc/pf.anchors/com.pow"

ykhddeiMac:etc ykhd$ sudo pfctl -f /etc/pf.conf
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
ykhddeiMac:etc ykhd$ sudo pfctl -e
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled

this is why？ OS X 10.11.3  Is there a problem？

**Comment by koenpunt** [comment]
I mean that it's not necessary, just append to the main rule:

```
echo "rdr pass proto tcp from any to any port {80,20559} -> 127.0.0.1 port 20559" | pfctl -Ef -
```

See also #521

**Comment by davidmoore-io** [comment]
This is worth a look if you're having the same symptoms on 10.11.x and are running an openVPN client.

https://github.com/basecamp/pow/issues/524.

**Comment by wujinhong** [comment]
No ALTQ support in kernel
ALTQ related functions disabled
ykhddeiMac:etc ykhd$ sudo pfctl -e
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled
what is wrong? Does someone know the reason? OS X is 10.11.6 (15G31)

**Comment by uxp** [comment]
The `No ALTQ support in kernel` messages can be ignored. 

Basically, ALTQ is "Alternate Queueing", which is used for [Quality of Service (QoS)](https://en.wikipedia.org/wiki/Quality_of_service). This just enables one to configure queues within PF to prefer certain types of network traffic to have priority over others (e.g. VoIP over Torrents). No one here should be needing this with regards to Pow. 

FreeBSD's GENERIC kernel ships without ALTQ support, as does MacOS' XNU Kernel. ALTQ is an *optional*, but preferred feature when using OpenBSD's PF Firewall. In order to enable ALTQ, one has to recompile the FreeBSD kernel with said support. Since we don't need this *optional* feature, and because recompiling the XNU kernel and including ALTQ is way beyond the scope of this issue with Pow, we can safely ignore this message.

https://www.freebsd.org/doc/handbook/firewalls-pf.html#idp76909288

**Comment by bjensen** [comment]
Is this a closed issue? I still have to do the following after each restart: 

``` sudo pfctl -f /etc/pf.conf; sudo pfctl -e```  High Sierra. Pow 0.6.0 installed using homebrew...

**Comment by koenpunt** [comment]
Have a look at [puma-dev](https://github.com/puma/puma-dev) instead. This is also mentioned in the [MANUAL.md](https://github.com/basecamp/pow/blob/master/MANUAL.md#version-history)

**Comment by bjensen** [comment]
@koenpunt puma-dev works with unicorn?

**Comment by koenpunt** [comment]
@bjensen no, with Puma. But would that be a problem, to use a different server in development? Also; is there a specific reason you're using unicorn?

**Comment by bf4** [comment]
Puma-dev can forward ports. I’ve used it with webpack. It can do unicorn

B mobile phone

**Comment by koenpunt** [comment]
@bf4 true, but that requires you to manually start the server
