### ISSUE TITLE
Can't turn on Anvil server anymore

### ISSUE THREAD

**Issue by edwardmp** [basecamp/pow#455]
When Anvil server is off, when I click on, I am prompted for my password.
After I enter my password, server is still off..

Any ideas?
![schermafbeelding 2014-06-19 om 03 13 54](https://cloud.githubusercontent.com/assets/1686739/3322627/0bccf920-f74f-11e3-8382-3e597033bd3f.png)

**Comment by Juandresyn** [comment]
Check for updates of Oh my ZSH

If oh my zsh is asking for updates, it wont let pow start, reinstall o restart from anvil

True Story
