### ISSUE TITLE
"LoadError: cannot load such file -- bundler/setup" with the fish shell?

### ISSUE THREAD

**Issue by chengguangnan** [basecamp/pow#470]
I'm using fish shell, rvm, osx 10.10.

My login shell is fish and pow 1.5.0 gives the "LoadError: cannot load such file -- bundler/setup" error.

Any ideas on how to fix this problem for fish? It's a really good shell.

**Comment by ewilliam** [comment]
i'm dealing with this error in fish but with chruby instead of RVM. sourcing chruby.sh and `chruby 2.3.1` doesn't work. any ideas?

**Comment by ewilliam** [comment]
^^^ nevermind, sourcing chruby works. i forgot to install bundler in new ruby
