### ISSUE TITLE
Can't uninstall: sh: line 65: [: ==: unary operator expected

### ISSUE THREAD

**Issue by hakunin** [basecamp/pow#496]
michal@10:57:06:~/dev/bis (support/strong-params)$ curl get.pow.cx/uninstall.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4389  100  4389    0     0   9414      0 --:--:-- --:--:-- --:--:--  9398
Sorry to see you go. Uninstall Pow [y/n]? 
sh: line 65: [: ==: unary operator expected

**Comment by hakunin** [comment]
hm, my bad. I didn't enter 'y' or 'n', just hit enter.

**Comment by guidobouman** [comment]
You can close issues yourself. =]
