### ISSUE TITLE
Chrome to force .dev domains to HTTPS via preloaded HSTS

### ISSUE THREAD

**Issue by adambutler** [basecamp/pow#545]
Details at https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by CydeWeys** [comment]
There hasn't been a commit in almost three years.  Looks like the project is abandoned :(

By the way, the HSTS preload list is used by all major browsers.  This isn't specifically a Chrome thing, it's about increasing the security of the TLD.

**Comment by vosechu** [comment]
I feel like we should also switch to using .test or .localhost instead of .dev. At least .test and .localhost are reserved and won't be sold to someone in the future.

**Comment by macowie** [comment]
It's already a configurable option, just a matter of updating the defaults (and documentation). In the meantime if you want to update it for yourself:

```
# ~/.powconfig

export POW_DOMAINS=dev,test
```

Then, [per the code comments](https://github.com/basecamp/pow/blob/163f546854b833bd8bb097cf9bad5be8420da727/src/configuration.coffee#L91), reinstall for the resolver to pick up the updates
```
$ sudo /path/to/pow --install-system
$ touch ~/.pow/restart.txt
```

**Comment by jeremy** [comment]
Switched from `.dev` to `.test` #547
